import type {Metadata} from "next";
import "../styles/global.css";

export const metadata: Metadata = {
    title: "Rahul Ramesh | Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
