import type {Metadata} from "next";
import "../styles/global.css";
import Toast from "@/components/toast";

export const metadata: Metadata = {
    title: "Rahul Ramesh | Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Toast />
                {children}
            </body>
        </html>
    );
}
